arb-dir: lib/l10n
template-arb-file: intl_ru.arb
output-localization-file: app_localizations.dart
output-dir: lib/src/localization
nullable-getter: false
fallback-strategy: base_locale
supported-locales: ["en", "ru"]